sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yangzidemuou521-

  # 华为OBS配置
  huaweiobs:
    endpoint: obs.cn-south-1.myhuaweicloud.com
    access-key-id: THE2LHNGEV4M14NLWFYE
    access-key-secret: 78ZBTPWP6EqtmDpkOmc4lEPjnxi44n2fraCq5ehC
    bucket-name: sky-take

  # 微信小程序配置
  wechat:
    appid: wxcadbf186a7185748
    secret: 1c0e0fee0d44e1dc9e5484ccb217b27e