server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    # pageHelper分页插件有循环依赖，不开启会报错
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    # 开启驼峰命名规则映射  表 user_name  -> 实体类 userName
    map-underscore-to-camel-case: true
    # 控制台打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret: itcast

    admin-ttl: 7200000

    admin-token-name: token
